// ALL ACTION TYPES
export enum actionTypes {
  ARTICLE_TEST_ACTION = '@ARTICLE/TEST_ACTION',
  ARTICLE_CREATE = '@ARTICLE/CREATE',
  ARTICLE_READ = '@ARTICLE/READ',
  ARTICLE_UPDATE = '@ARTICLE/UPDATE',
  ARTICLE_DELETE = '@ARTICLE/DELETE'

}
